In [1]:
import pandas as pd
import os

In [2]:
#Files to load
school_files_to_load = "Resources/schools_complete.csv"
student_data_to_load = "Resources/students_complete.csv"

In [3]:
school_data= os.path.join("Resources", "schools_complete.csv")
student_data= os.path.join("Resources", "students_complete.csv")

school_data_df= pd.read_csv(school_data)
student_data_df= pd.read_csv(student_data)

In [4]:
student_data_df.head()

,Student ID,student_name,gender,grade,school_name,reading_score,math_score
0,0,Paul Bradley,M,9th,Huang High School,66,79
1,1,Victor Smith,M,12th,Huang High School,94,61
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58
4,4,Bonnie Ray,F,9th,Huang High School,97,84

In [5]:
school_data_df.count()

School ID      15
school_name    15
type           15
size           15
budget         15
dtype: int64

In [6]:
student_data_df.count()

Student ID       39170
student_name     39170
gender           39170
grade            39170
school_name      39170
reading_score    39170
math_score       39170
dtype: int64

In [7]:
student_data_df.isnull().sum()

Student ID       0
student_name     0
gender           0
grade            0
school_name      0
reading_score    0
math_score       0
dtype: int64

In [8]:
student_data_df.notnull().sum()

Student ID       39170
student_name     39170
gender           39170
grade            39170
school_name      39170
reading_score    39170
math_score       39170
dtype: int64

In [9]:
missing_values= os.path.join("Resources", "missing_grades.csv")

In [10]:
missing_values_df= pd.read_csv(missing_values)

In [11]:
missing_values_df.count()

Student ID       8
student_name     8
gender           8
grade            8
reading_score    7
math_score       7
dtype: int64

In [12]:
missing_values_df.dropna()

   Student ID       student_name gender grade  reading_score  math_score
0           0       Paul Bradley      M   9th           66.0        79.0
1           1       Victor Smith      M  12th           94.0        61.0
3           3  Dr. Richard Scott      M  12th           67.0        58.0
4           4         Bonnie Ray      F   9th           97.0        84.0
6           6      Sheena Carter      F  11th           82.0        80.0
7           7       Nicole Baker      F  12th           96.0        69.0

In [13]:
missing_values_df.fillna(85)

   Student ID       student_name gender grade  reading_score  math_score
0           0       Paul Bradley      M   9th           66.0        79.0
1           1       Victor Smith      M  12th           94.0        61.0
2           2    Kevin Rodriguez      M  12th           85.0        60.0
3           3  Dr. Richard Scott      M  12th           67.0        58.0
4           4         Bonnie Ray      F   9th           97.0        84.0
5           5      Bryan Miranda      M   9th           94.0        85.0
6           6      Sheena Carter      F  11th           82.0        80.0
7           7       Nicole Baker      F  12th           96.0        69.0

In [14]:
student_names= student_data_df["student_name"].tolist()
student_names

['Paul Bradley',
 'Victor Smith',
 'Kevin Rodriguez',
 'Dr. Richard Scott',
 'Bonnie Ray',
 'Bryan Miranda',
 'Sheena Carter',
 'Nicole Baker',
 'Michael Roth',
 'Matthew Greene',
 'Andrew Alexander',
 'Daniel Cooper',
 'Brittney Walker',
 'William Long',
 'Tammy Hebert',
 'Dr. Jordan Carson',
 'Donald Zamora',
 'Kimberly Santiago',
 'Kevin Stevens',
 'Brandi Lyons',
 'Lisa Davis',
 'Kristen Lopez',
 'Kimberly Stewart',
 'Christopher Parker',
 'Chelsea Griffith',
 'Cesar Morris',
 'Melanie Decker',
 'Tracey Oconnor',
 'Kelly James',
 'Nicole Brown',
 'Bobby Harris',
 'Brian Fernandez',
 'Candace Phelps',
 'Amy Gonzalez',
 'Steven Green',
 'Benjamin Carlson',
 'Kevin Bailey',
 'Jesse Newton',
 'Kimberly Mercado',
 'Gregory Roberts',
 'Matthew Mayer',
 'Jennifer Parks',
 'John Carlson',
 'Megan Roberts',
 'Debra Flores',
 'Heidi Jackson',
 'Denise Bradford',
 'Ellen Brown',
 'Amy Perkins',
 'Natalie Mitchell',
 'Tiffany Gutierrez',
 'Jennifer Hess',
 'Christine Fletcher',
 'Jon Smith',
 'Tracey Yates',
 'Jerry Gordon',
 'Michael Cox',
 'Madeline Snyder MD',
 'Allison King',
 'Theresa Meyer',
 'Jared Wood',
 'Eric Maynard',
 'Mark Owens',
 'Ronnie Conley',
 'Kimberly Davis',
 'Amy Mitchell',
 'Mr. Dylan Taylor MD',
 'Elizabeth Henderson',
 'James Lopez',
 'Michael Morgan',
 'Angela Francis',
 'Breanna Taylor',
 'Jason Johnson',
 'Kyle Martin',
 'Dr. Scott Gill',
 'Lisa Long',
 'Erin Liu',
 'Marcus Richards',
 'Jason Thompson',
 'Elizabeth Mckinney',
 'Jessica Bailey',
 'Lisa Frye',
 'Lindsey Baker',
 'Lisa Ramirez',
 'Joseph Butler',
 'Tina Lynch',
 'Leah Benitez',
 'Elizabeth Parker',
 'Melissa Hunter',
 'Miss Madison Everett',
 'Ronald Garcia',
 'Mark Cherry',
 'Ryan Stokes',
 'Isaiah Maldonado',
 'Micheal Dennis',
 'Kevin Martinez',
 'Jessica Smith',
 'Dawn Trujillo',
 'Virginia Ramirez MD',
 'Marc Hernandez',
 'Jose Gonzalez',
 'Jason Dennis',
 'Gary Morris',
 'William Mcdonald',
 'Michael Savage',
 'Alexis Todd',
 'David Hansen',
 'Steven Mendez',
 'Ryan Lynch',
 'Timothy Marks',
 'Alexander Johns',
 'Kenneth Chavez',
 'Dennis Williams',
 'Michael Roy',
 'Richard Ryan',
 'Matthew Reyes',
 'Stephanie Ward',
 'Christopher Tucker',
 'Daniel Jones',
 'Devin Craig',
 'Erin Prince',
 'Bernard Ortiz',
 'Nicole Miller',
 'Christopher Fritz',
 'Bonnie Mckinney',
 'Troy Nelson',
 'Jennifer Lee',
 'Ronald Ward',
 'Nathaniel Hampton',
 'Michael Travis',
 'James Taylor',
 'Thomas Strickland',
 'Brittany Jackson',
 'Marisa Lowe',
 'Nicole Thomas',
 'Matthew Rodriguez',
 'Kent Fernandez',
 'Michelle Martin',
 'John Sparks',
 'Ann Blake',
 'Melissa Miller',
 'Steven Houston',
 'Kristen Anderson',
 'Cory Jones',
 'Jennifer Mora',
 'Dennis Griffin',
 'Darryl Brown',
 'Martin Mosley',
 'Joyce Diaz',
 'Jeffrey Rose',
 'Jamie Moreno',
 'Catherine Williams',
 'Lauren Byrd',
 'Vanessa Frazier',
 'Stephen Bryant',
 'Lawrence Liu',
 'Joseph Larsen',
 'Susan Collier',
 'Meagan Jensen',
 'Julie Harper',
 'Meghan Carroll',
 'Wanda Horton',
 'Mary Campbell',
 'Jennifer Rodgers',
 'Heather Cooper',
 'Ryan Perez',
 'Ryan Cox',
 'Darren Zavala',
 'Joseph Morales III',
 'Aaron West',
 'James Combs',
 'Curtis Garner',
 'Sarah Miller',
 'Samantha Thomas',
 'Robert Atkins',
 'Alexis Crawford',
 'Ryan Maddox',
 'Jonathan Meyer',
 'Donna Wagner',
 'William Kennedy',
 'Kimberly Martinez',
 'Matthew Anderson',
 'Kari Miller',
 'Jenna Luna',
 'Justin Contreras',
 'Mary Fox',
 'Joseph Perkins',
 'Kelly Phillips',
 'Justin Thornton',
 'Joshua Barber',
 'Travis Jackson',
 'Jordan Beasley',
 'Kevin Allen',
 'Victoria Harris',
 'Victoria Joseph',
 'Brandy Marshall',
 'Ryan Jimenez',
 'Michael Chan',
 'Christopher Phillips',
 'Kevin Murphy',
 'Vanessa Harper',
 'James Ferguson',
 'Carol Schroeder',
 'Jerry Phillips',
 'Kristin Wade',
 'Jessica Warner',
 'Dorothy Burke',
 'Bethany Walter',
 'Melissa Avery',
 'Daniel Sutton',
 'Ryan Johnson',
 'Timothy Quinn',
 'Zachary Allen',
 'Lauren Schmitt',
 'Stephanie Armstrong',
 'Ruben Rivera',
 'Patricia Petty',
 'Joseph Jacobs',
 'Bianca Wilson',
 'Donald Perez',
 'Curtis Gomez',
 'Courtney Brown',
 'Nicole Randall',
 'Steven Lambert',
 'Anthony Alvarez',
 'Shawn Farrell',
 'Jesus Schmidt',
 'Laura Wright',
 'Steven Smith',
 'Norman Thompson',
 'Anthony Wright',
 'Kayla Watts',
 'Aimee Johnson',
 'Heidi Scott',
 'Anthony Williams',
 'Sarah Hill',
 'Kim Wang',
 'Beth Manning',
 'Ryan Hanson',
 'James Wood',
 'Corey Greene',
 'John Carter',
 'Beth Garza',
 'Karen Jones',
 'Stephanie Poole',
 'Lisa Brown',
 'Paul Scott',
 'Evelyn Buck',
 'Terry Harrell',
 'Leah Skinner',
 'Anthony Mercado',
 'Walter Kelly',
 'Lori Evans',
 'Ashley Jones',
 'Amber Soto',
 'Patrick Phillips',
 'Linda Curry',
 'Alexander Obrien',
 'Vincent Garza',
 'Terry Marsh',
 'Angela Perkins DVM',
 'Peter Hampton',
 'David Cross',
 'Clinton Ortega',
 'Jamie Escobar',
 'Sandra Mason',
 'Craig Cole',
 'Lisa Warren',
 'Maria Howard',
 'Michael Porter',
 'John Turner',
 'Timothy Wang',
 'Amanda Taylor',
 'Karen Mckenzie',
 'Brandon Miles',
 'Christina Whitaker',
 'Nicole Peterson',
 'Ashley Moore',
 'Todd Carrillo',
 'Robert Williams',
 'Ashley Jones',
 'Vanessa Parker',
 'Robert Carlson',
 'Jared Lewis',
 'Christopher Hernandez',
 'Kimberly Harris',
 'Katrina Hill',
 'Heather Lee',
 'Donald Harmon',
 'Elizabeth Sanders',
 'Richard Ramsey',
 'Carmen Johnson',
 'Elaine Osborne',
 'Kent Burns',
 'Meagan Smith',
 'Craig Hahn',
 'Jeremy Wu',
 'Aaron Rodriguez',
 'Matthew Taylor',
 'Diana Evans',
 'Michele Pearson',
 'Erik Wagner',
 'Maria Welch',
 'Debra Martin',
 'Devon Conner',
 'Christine Patel',
 'David Lopez',
 'Nathan Baird',
 'Samuel Castillo',
 'Rebecca Payne',
 'Carl Johnson',
 'William Adams',
 'Paula Harrison',
 'Wayne Atkinson',
 'Lindsay Frank',
 'Jose Garcia',
 'Andrew Gaines',
 'Rachael Liu',
 'Donald Lewis',
 'Shane Edwards',
 'Todd Levy',
 'Joanna Moore',
 'Michael Lewis',
 'James Robinson',
 'Jeffrey Arellano',
 'Heather Allen MD',
 'Lori Villarreal',
 'Robert Harper',
 'Karen Villegas',
 'Tracey Crane',
 'Elizabeth Allen',
 'Jorge Lynn',
 'Harold Gordon',
 'Nicholas Mcclain',
 'Tanya Harris',
 'Amy Smith',
 'Kathy Morse',
 'Andrea Wood',
 'Maureen Massey',
 'Daniel Smith',
 'Alexandra Smith',
 'Caitlin Hall',
 'Jose Carlson',
 'Deborah Macias',
 'Dwayne Rice',
 'Matthew Harris',
 'Eric Bowman',
 'Samuel Ali',
 'David Miller',
 'James Moreno',
 'Brooke Austin',
 'Alisha Martin',
 'Neil Rodriguez',
 'Gary Williams',
 'Michael Pittman',
 'Stephanie Palmer',
 'Christine Perry',
 'Suzanne David',
 'Amber Smith',
 'Ryan Jones',
 'Emily Ford',
 'Kelsey Shea',
 'Katherine Wallace',
 'Erica Conway',
 'Tyler Parker',
 'Michael Parks',
 'Elizabeth Hunt',
 'Grant Jackson',
 'Daniel Matthews',
 'Diana Silva',
 'Frank Garza',
 'Terri Fischer',
 'Robert Goodwin',
 'Bobby Ruiz',
 'Stephanie Taylor',
 'Erin Hill',
 'Erin Cohen',
 'Jeffrey Morris',
 'Elizabeth Simpson',
 'Jennifer Davis',
 'Rachel Burton',
 'Joseph Wilkins',
 'Lawrence Montgomery',
 'Patricia Howard',
 'Jessica Hanson',
 'Donna Dean',
 'Edwin Reid',
 'Jodi Brown',
 'Elizabeth Richard',
 'Aaron Martinez',
 'Stephen Fischer',
 'Diana Reeves',
 'Jeffrey Eaton',
 'Evelyn Miller',
 'Christopher Kidd',
 'Sarah Adams',
 'Melinda Nelson',
 'Kevin Brooks',
 'John Bowen',
 'Tracie Abbott',
 'Allen Foster',
 'Kathryn Elliott',
 'Christopher Walker',
 'Cynthia Martin',
 'Amanda Bennett',
 'Dennis Padilla',
 'Antonio Miller',
 'Melissa Trevino',
 'Andrew King',
 'John Martinez',
 'Lauren King',
 'Stephanie Mercado',
 'William Smith',
 'Jonathan Marshall',
 'Luke Lowery MD',
 'Emily Reynolds',
 'Kevin Mclean',
 'Elizabeth Taylor',
 'Pamela Rivas',
 'Tammy Martin',
 'Holly Watkins',
 'Patrick Chen',
 'Michelle Griffin',
 'Theresa Andrews',
 'Alan Henry',
 'Dr. Larry Hines',
 'Travis Frazier',
 'Julie Jones',
 'Natalie Reynolds',
 'Jessica Cohen',
 'Jason Robinson',
 'Heather Palmer',
 'Emily Cardenas MD',
 'Scott Glover',
 'Jacqueline White',
 'Mrs. Elizabeth Espinoza DDS',
 'Toni Porter',
 'Jennifer Mejia',
 'Brenda Peterson',
 'Paul Hamilton',
 'Patricia Nguyen',
 'James Ho',
 'Elizabeth Cohen',
 'Stephanie Lane',
 'Dawn Rhodes',
 'Theresa Robinson',
 'Breanna Mosley',
 'Carmen Wilson',
 'Ian Brown',
 'Kathleen Matthews',
 'Bryan Diaz',
 'Gina Sweeney',
 'Alan Garcia',
 'Erik Wheeler',
 'Stephanie Robles',
 'Samantha Hanson',
 'Christopher Williams',
 'Stephanie Hart',
 'Mrs. Lisa Becker',
 'Bianca Johnson',
 'Amy Steele',
 'Gina Contreras',
 'Jaime Alexander',
 'Kevin Coleman',
 'Caitlin Williams',
 'Joseph Lloyd',
 'Carrie Hernandez',
 'Mr. Travis Young',
 'Francis Wright',
 'Joel Harper',
 'Eduardo Park',
 'Melissa Yoder',
 'Donna Campbell',
 'Connie Delacruz',
 'Luis Parker',
 'Pamela Watts',
 'Lindsey Mitchell',
 'Brenda Price',
 'Joseph Howard',
 'Amy Evans',
 'Paula Fernandez DVM',
 'Amber Cunningham',
 'Preston Wheeler',
 'James Lopez',
 'Chad Drake',
 'Samuel Blackburn',
 'Shawn Nielsen',
 'Eric Perez',
 'Kevin Montgomery',
 'Terry Thomas',
 'Kim Meyer',
 'Michael Townsend',
 'Ronnie Rodriguez',
 'Savannah Smith',
 'Shane Nguyen',
 'Michael Brown',
 'Robert Young',
 'Daniel Griffin',
 'James Johnson',
 'Mary Cox',
 'Tina Aguirre',
 'Jillian Mcdonald',
 'Matthew Branch',
 'Christopher Jordan',
 'Victor Mcguire',
 'Erin Arnold',
 'Nicholas Wu',
 'Kristen Wilson',
 'Morgan Moore',
 'Stephen Smith',
 'Jeremy Romero',
 'Julie Bush',
 'Brittany Taylor',
 'James Kim',
 'Ashley Roberts',
 'Brandon Johnson',
 'David Davenport',
 'Mark Washington',
 'Alicia Marshall',
 'Barbara Santana',
 'Samantha Parker',
 'Joseph Walters',
 'Michael Zamora',
 'Kyle Cobb',
 'Jill Clark',
 'Sarah Warren',
 'Jennifer Robinson',
 'Patricia Johnson',
 'Henry Evans',
 'Alexander Ramsey',
 'Brandon Stephens',
 'Jeff Holland',
 'Samuel Schultz',
 'Brett Johnson',
 'Daniel Sherman',
 'Justin Mccall',
 'Jonathan Evans',
 'Jacqueline Kennedy',
 'Martin Stephenson',
 'Lindsey Lane',
 'Jessica Hart',
 'Edward Lucas',
 'Lisa Osborne',
 'Hannah Black',
 'Alexander Paul',
 'Brenda Wong',
 'Thomas Delgado',
 'Jeremy Sutton',
 'Paula Donaldson',
 'Valerie Thompson',
 'John Schaefer',
 'Jesus Manning',
 'Tyrone Lawson',
 'Carl May',
 'Brittany Russell',
 'Philip Edwards',
 'Robert Aguilar',
 'Aaron Russo',
 'Tracy Andrade',
 'Amy Sullivan',
 'Howard Beck',
 'Dr. Xavier Bell II',
 'Dawn Schultz',
 'Caleb Lucas',
 'Barbara Gonzalez',
 'Charles Yang',
 'David Gallagher',
 'Bethany Vargas',
 'Jennifer Schultz',
 'Paula Marshall',
 'Jordan Elliott',
 'Samantha Mcmillan',
 'Judith Johnson',
 'Grace Palmer',
 'Brandon Ramirez',
 'Carol Smith',
 'Matthew Odom',
 'Erika Gray',
 'Donna Kramer',
 'Jonathan Snyder',
 'Frank Howe',
 'Amy Beck',
 'Lori Holmes',
 'Rebekah Hampton',
 'Perry Bishop',
 'Andrew Hanson MD',
 'Jody Hughes',
 'Anna Garcia',
 'Colleen Walker',
 'Danny Bridges',
 'Kristina Ford',
 'Sabrina Davidson',
 'Alexander Freeman',
 'Jack Davis',
 'Victor Rivera',
 'Elizabeth Pena',
 'Neil Castro',
 'Michael Briggs',
 'Anna Andersen',
 'Elizabeth Oconnor',
 'Zachary Brooks',
 'Scott Jackson',
 'Mary Fuentes',
 'Denise Reyes',
 'Janice Collier',
 'Tina Barber',
 'Keith Rojas',
 'Michelle Decker',
 'James Smith',
 'Alexandra Thompson',
 'Jacqueline Campbell',
 'Austin Clark',
 'Brooke Thomas',
 'Molly Smith',
 'Pamela Beck',
 'Timothy Morris',
 'Lauren White',
 'Jessica Beltran',
 'Alexandra Jones',
 'Evelyn Rice',
 'Stephen Ellis',
 'Caroline Smith',
 'Fred Case',
 'Crystal Anderson',
 'Jordan Gross',
 'Marie Harris',
 'Charles Hayes',
 'Beverly Sheppard',
 'Denise Solis',
 'Alexander Myers',
 'Sally Robertson',
 'Steven Morris',
 'Nina Flores',
 'Miguel Patterson',
 'John Simpson',
 'Charles Cruz',
 'Monica Davis',
 'James Fields',
 'Kevin Frederick',
 'Jeremy Soto',
 'Ronald Harris',
 'Carol Stewart',
 'Albert Durham',
 'James Sanchez',
 'John Adams',
 'Cody Williams',
 'Ernest Love',
 'Tommy Smith',
 'Jared Anderson',
 'Jennifer Yang',
 'Joe Mercado',
 'Mr. Roberto Wright MD',
 'Michael Smith',
 'William Park',
 'Benjamin Williams',
 'Dean Perez',
 'Mr. Dale Miller',
 'Marissa Russell',
 'Mary Gonzalez DDS',
 'April Jackson',
 'William Hayes',
 'Meghan Holloway',
 'Amy Coleman',
 'James Green',
 'Michael Tran',
 'Joseph Cortez',
 'Anita Moss',
 'Benjamin Stokes',
 'Michael Li',
 'Alexander Rosales',
 'Katie Dawson',
 'Shelly Erickson',
 'Kathryn Turner',
 'Jacob Lee',
 'Ryan Smith',
 'Joshua Fernandez',
 'Mia Roach',
 'William Rodriguez',
 'Wanda Cruz',
 'Pamela Hall',
 'David Smith',
 'Jason Brown',
 'Chelsea Alexander',
 'Kimberly Tate',
 'Daniel Williams',
 'Terri Jacobson',
 'Paul Harris',
 'Jessica Thompson',
 'Nancy Hawkins',
 'Deborah Phillips',
 'Mark Mendoza',
 'Stephen Williamson',
 'Jennifer Strong',
 'Matthew Moore',
 'Raymond Parker',
 'Lee Evans',
 'Curtis Rodriguez',
 'Sara Morris',
 'Dawn Palmer',
 'Brianna Benson',
 'Luis Watts',
 'Mrs. Cindy Brown',
 'Summer Sandoval',
 'Ashley Smith',
 'Randy Wallace',
 'Angela Simmons',
 'Sandra Haley',
 'George Morgan',
 'Melissa Ali',
 'Matthew Oliver',
 'Michael Kirk',
 'Terry Khan',
 'Kristie Elliott',
 'Joel Campbell',
 'Anthony Henderson',
 'Brent Christensen',
 'Heidi Hayes',
 'Ryan Mcbride',
 'Kyle Murillo',
 'Angela Powell',
 'Jeanette Simmons',
 'Adam Vance',
 'Kristen Murray',
 'Jessica Burnett',
 'Alex Walker',
 'Robert Phillips',
 'Elizabeth Martinez',
 'Kristina Young',
 'Sarah Morgan',
 'Cheryl Harding',
 'Keith Hunter',
 'Todd Williams',
 'James White MD',
 'Kyle Johnson',
 'Andrea Suarez',
 'Michael Sanchez',
 'Jaime Torres',
 'Donald Gill DDS',
 'Austin Lee',
 'Adrian Bowman',
 'Julie Perez',
 'Debra Maxwell',
 'Bradley Phillips',
 'Sonya Simmons',
 'Eric Miller',
 'Charles Berger',
 'Mary Monroe',
 'Destiny Burns',
 'Patrick Khan',
 'Nathaniel Henson',
 'Larry Miller',
 'Timothy French',
 'Xavier Mitchell',
 'Jason Crosby',
 'Joshua Johnson',
 'Alyssa Clark',
 'Jonathan Cooper',
 'Mark Hunt',
 'Norman Moore',
 'Brian Atkins',
 'Zachary Jones',
 'Danielle Wong',
 'Patricia Lane',
 'Joshua Rose',
 'Hannah Montes',
 'Mrs. Catherine Williams MD',
 'Michael Jenkins',
 'James Scott',
 'Evan Ballard',
 'Andrea Miller',
 'Jasmine Lynch',
 'Jennifer Fox',
 'Jared Castro',
 'Eugene Cox',
 'Wendy Wilson',
 'Debbie Smith',
 'Michael Fletcher',
 'Jay Waters',
 'Melissa Martinez',
 'Cory Howard',
 'Mitchell Hanson',
 'Corey Boyer',
 'Elizabeth Gonzalez',
 'Robert Hutchinson',
 'David Hernandez',
 'Tammy Jordan',
 'Denise Johnson',
 'Brandi Copeland',
 'Evan Marshall',
 'Gregory Long',
 'Kristen Underwood',
 'Walter French',
 'Edwin Thompson',
 'Edward Rivera',
 'Brandon Wilson',
 'Alejandra Todd',
 'Dana Hoffman',
 'David Howard',
 'Ashley Caldwell MD',
 'Cindy Horn',
 'Kevin Armstrong',
 'Stacey Porter',
 'Patrick Hunt',
 'David White',
 'Tammy Black',
 'Joanna Williams',
 'Becky Moran',
 'Brenda Smith',
 'Gabrielle Webb',
 'Mr. Jared Campbell',
 'Ryan Jenkins',
 'Thomas Shepard',
 'Jeremiah Boyd',
 'Matthew White',
 'Christina Anderson',
 'Edward Olson',
 'Emily Bryant',
 'Amy Guzman',
 'Kathleen Owens',
 'John Davila',
 'Nicole King',
 'Jason Villarreal',
 'Matthew Washington',
 'Peter Simpson',
 'Cristian Espinoza',
 'Steven Fry',
 'David Miller',
 'Tamara Hernandez',
 'Jordan Lewis',
 'Carol Anderson',
 'Michael Moreno PhD',
 'Nicholas Logan',
 'Paul Anderson',
 'Jason Young',
 'Wesley Martin',
 'Karen Wall',
 'Tara Parker MD',
 'Michael Reyes',
 'Amy Henderson',
 'Jessica Reed',
 'Joseph Miranda',
 'Mackenzie Jones',
 'Jon Espinoza',
 'Kelly Medina',
 'Jason Rubio',
 'Jennifer Munoz',
 'Christopher Warner',
 'Vincent Thomas',
 'Andrew Young',
 'David Jenkins',
 'Daniel Stephens',
 'Elizabeth Lewis',
 'Aaron Moore',
 'Lisa Hogan',
 'Shawn Williams DVM',
 'Michele Dickerson',
 'Dr. Alicia Martinez',
 'Mr. Timothy Anderson',
 'Sierra Jackson',
 'Sharon Taylor',
 'Jeffrey Smith',
 'Mark Taylor',
 'Christina Ross',
 'Judy Hall',
 'Jennifer Fox',
 'Kenneth Moran',
 'Gerald Ferguson',
 'Albert Carter',
 'Michael Reilly',
 'Kathleen Schwartz',
 'Stacey Harris',
 'Mrs. Paula Lee',
 'Adrian Black',
 'Rita Moreno',
 'Jason Perry',
 'Scott Ortiz',
 'Randy Mueller',
 'Samantha Anderson',
 'Phillip Brown',
 'Christina Kerr',
 'Derrick Hill',
 'Nathan Bond',
 'Marie Wilson',
 'Caitlin Jones',
 'Barbara Campbell',
 'Katie Gonzales',
 'Mr. Elijah Hall',
 'James Sanders',
 'Nicholas Martinez',
 'Maria Mack',
 'Mary Mason',
 'Tiffany Campbell',
 'Mr. Raymond Stone',
 'Dominique Henderson',
 'Martin Williams',
 'Hannah Parker',
 'Susan Webb',
 'Rachel Johnson',
 'Darren Davis',
 'Tim Carr',
 'Jesus Ryan',
 'John Hays',
 'Scott Stewart',
 'Alexandra Roberts',
 'Amanda Norman',
 'James Moody',
 'Brenda Jones',
 'Kathy Smith',
 'Raymond Clark',
 'Ashley Martin',
 'Tamara Flowers',
 'Cesar Hanson',
 'Ross Strickland',
 'Randy Moore',
 'Henry Andersen',
 'Paul Martin',
 'Sarah Stanley',
 'Jordan Lewis',
 'Ashley Richardson',
 'Michael Brown',
 'Jason Davis',
 'Wendy Mcclain',
 'Troy Williams',
 'Carrie Alexander',
 'Kyle Ware',
 'Michael Robinson',
 'Roger Wilson',
 'Teresa Fuller',
 'Craig Silva',
 'Duane Thomas',
 'Jon Crosby',
 'Jon Steele',
 'Daniel Shaw',
 'Gwendolyn Williams',
 'Angela Hess',
 'Cameron Arnold',
 'Janice Garcia',
 'Anne Bullock',
 'Katie Moody',
 'Kayla Rivas',
 'Danny Pearson',
 'Billy Robles',
 'Michelle Delgado',
 'Cindy Harrison',
 'John Dickerson MD',
 'Tina Armstrong',
 'Mr. Alex Franklin',
 'Ryan King',
 'Christine Guzman',
 'Helen Malone',
 'Benjamin Carpenter',
 'Mrs. Jessica Dunn',
 'Jessica Kaiser',
 'Brandon Black',
 'David Hernandez',
 'Brenda Turner',
 'Katherine Black',
 'Larry Santos',
 'Zachary Dominguez',
 'Tanya Fernandez',
 'Joseph Nichols',
 'Rebecca Martinez',
 'Traci Ramirez',
 'Ryan Bauer',
 'Joshua Williams',
 'Devon Foley',
 'Heidi Walter',
 'Mario Nguyen',
 'Jordan Hernandez',
 'William Miller',
 'Nicholas Chung',
 'Christine Cooley',
 'Carrie Nelson',
 'Crystal Fowler',
 'Lori Taylor',
 'Mr. Michael Stevenson',
 'Matthew Holmes',
 'David Walls',
 'Megan Martin',
 'Karen Peterson',
 'Kristen Wallace',
 'Mark Peterson',
 'Jason Jones DDS',
 'Keith Barber',
 'Patrick Green',
 'Antonio Lopez',
 'Travis Peterson',
 'Gabriel Hunter',
 'Amanda Ross',
 'Samuel Thompson',
 'Robert Bowman',
 'Cynthia Cox',
 'Brittany Miller',
 'Eric Torres',
 'Sandra Calhoun',
 'Jacob Bailey',
 'Jessica Harris',
 'Molly Carr',
 'Keith Davis',
 'Adriana Wade MD',
 ...]

In [16]:
name= "Mrs. Linda Santiago"
name.split()

['Mrs.', 'Linda', 'Santiago']

In [20]:
students_to_fix= []

for name in student_names:
   if len(name.split()) >= 3:
    students_to_fix.append(name)
    
len (students_to_fix)

1531

In [22]:
prefixes = []
for name in students_to_fix:
    if len(name.split()[0]) <= 4:
        prefixes.append(name.split()[0])

suffixes= []
for name in students_to_fix:
    if len(name.split()[2]) <= 3:
        suffixes.append(name.split()[-1])

In [24]:
set(prefixes)
set(suffixes)

{'Cox',
 'DDS',
 'DVM',
 'Day',
 'II',
 'III',
 'IV',
 'Jr.',
 'Kim',
 'Lee',
 'Li',
 'MD',
 'PhD',
 'Roy'}

In [33]:
prefixes_suffixes = ["Dr. ", "Mr. ","Ms. ", "Mrs. ", "Miss ", " MD", " DDS", " DVM", " PhD"]
for word in prefixes_suffixes:
    student_data_df["student_name"]= student_data_df["student_name"].str.replace(word, "")

,Student ID,student_name,gender,grade,school_name,reading_score,math_score
0,0,Paul Bradley,M,9th,Huang High School,66,79
1,1,Victor Smith,M,12th,Huang High School,94,61
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60
3,3,Richard Scott,M,12th,Huang High School,67,58
4,4,Bonnie Ray,F,9th,Huang High School,97,84
...,...,...,...,...,...,...,...
39165,39165,Donna Howard,F,12th,Thomas High School,99,90
39166,39166,Dawn Bell,F,10th,Thomas High School,95,70
39167,39167,Rebecca Tanner,F,9th,Thomas High School,73,84
39168,39168,Desiree Kidd,F,10th,Thomas High School,99,90
39169,39169,Carolyn Jackson,F,11th,Thomas High School,95,75

151